// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8M6JGPtRGc4NjtF_Ma49hGM63DZbX6A',
    appId: '1:462471498103:web:0e3c6e2db5738c37b5f972',
    messagingSenderId: '462471498103',
    projectId: 'sakukita-d63a4',
    authDomain: 'sakukita-d63a4.firebaseapp.com',
    storageBucket: 'sakukita-d63a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN9198TbDDS1qhcBY4Ac8_L8nwJTZWjWU',
    appId: '1:462471498103:android:77ef946419673817b5f972',
    messagingSenderId: '462471498103',
    projectId: 'sakukita-d63a4',
    storageBucket: 'sakukita-d63a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzwdlTG9fezA0jMnXZUa4T1A3J0FZboW8',
    appId: '1:462471498103:ios:ad598434fc7bb341b5f972',
    messagingSenderId: '462471498103',
    projectId: 'sakukita-d63a4',
    storageBucket: 'sakukita-d63a4.firebasestorage.app',
    iosBundleId: 'com.example.sakukita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzwdlTG9fezA0jMnXZUa4T1A3J0FZboW8',
    appId: '1:462471498103:ios:ad598434fc7bb341b5f972',
    messagingSenderId: '462471498103',
    projectId: 'sakukita-d63a4',
    storageBucket: 'sakukita-d63a4.firebasestorage.app',
    iosBundleId: 'com.example.sakukita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr8M6JGPtRGc4NjtF_Ma49hGM63DZbX6A',
    appId: '1:462471498103:web:a07747af86f0c1f4b5f972',
    messagingSenderId: '462471498103',
    projectId: 'sakukita-d63a4',
    authDomain: 'sakukita-d63a4.firebaseapp.com',
    storageBucket: 'sakukita-d63a4.firebasestorage.app',
  );

}